name: Pull Request

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  quality-gates:
    name: Quality Gates
    uses: ./.github/workflows/quality-gates.yml
    secrets: inherit